application:
  kafka-topics:
    purchase-requests: flashsale.purchase.requests
  kafka-api-key: ${sm://kafka-api-key}
  kafka-api-secret: ${sm://kafka-api-secret}
  schema-api-key: ${sm://schema-registry-api-key}
  schema-api-secret: ${sm://schema-registry-api-secret}

spring:
  config:
    import: sm://
  profiles:
    active: local
  cloud:
    gcp:
      project-id: flashsale-456707
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS_PURCHASE_PROCESSOR}
  application:
    name: flashsale-purchase-processor
  kafka:
    bootstrap-servers: pkc-lzoyy.europe-west6.gcp.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
      acks: all
    properties:
      schema.registry.url: https://psrc-9mwvv.europe-west6.gcp.confluent.cloud
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: ${kafkaJaasConfig}
      basic:
        auth:
          credentials.source: USER_INFO
          user.info: ${schemaRegistryCredentials}
      ssl.endpoint.identification.algorithm: https
