application:
  kafka-topics:
    purchase-requests: flashsale.purchase.requests
    flashsale-events: flashsale.events

spring:
  profiles:
    active: local
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
      acks: all
    consumer:
      group-id: purchase-requests-consumer-group
  cloud:
    gcp:
      project-id: flashsale-456707
      credentials:
        location: file:${GOOGLE_APPLICATION_CREDENTIALS_PURCHASE_PROCESSOR}
      secretmanager:
        enabled: false
      core:
        enabled: false
