application:
  kafka-topics:
    purchase-requests: flashsale.purchase.requests
  kafka-api-key: ${sm://kafka-api-key}
  kafka-api-secret: ${sm://kafka-api-secret}
  schema-api-key: ${sm://schema-registry-api-key}
  schema-api-secret: ${sm://schema-registry-api-secret}

spring:
  cloud:
    gcp:
      project-id: flashsale-456707
  application:
    name: flashsale-purchase-processor
  kafka:
    bootstrap-servers: pkc-lzoyy.europe-west6.gcp.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
      acks: all
    properties:
      schema.registry.url: https://psrc-9mwvv.europe-west6.gcp.confluent.cloud
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
#        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='J5YLG33YCVT4PEPT' password='hZyaDytOW9Q1f1tM7oMlcET+x+At3+XtGF0GlE0+otbW+KPpDAr6uv8E1+s1yTGW';
        jaas.config: ${kafkaJaasConfig}
      basic:
        auth:
          credentials.source: USER_INFO
#          user.info: BPGNIASEDYFOAUIT:zS50DUuhtBetlMxuOAnpmWeCjuRB0OwjLDkAVI7ur4+pLjgssFHFJDEPivwCaxnD
          user.info: ${schemaRegistryCredentials}
      ssl.endpoint.identification.algorithm: https


